source "https://rubygems.org"

gem "kramdown"
gem "kramdown-parser-gfm"
gem "rouge"
gem "jekyll", "~> 3.10"
gem "jekyll-paginate"
gem "jekyll-paginate-content"
gem "json"
gem "wdm", ">= 0.1.0"
gem "base64"
gem "logger"
gem "bigdecimal"
gem "csv"
gem "ostruct"
gem "strscan"
